### ISSUE TITLE
Does ONOS support different deviceid for barefoot switch?

### ISSUE THREAD

**Issue by xfyan0408** [stratum/fabric-tna#526]

**Comment by xfyan0408** [comment]
In onos, the tofino-netcfg.json can specify deviceId through grpc url like `"managementAddress": "grpc://192.168.109.96:9559?device_id=1",`

but in barefoot-switch，I only know that I can run stratum with chassis_config.pb.txt to specify node_id, but it seems to only support `node = 1`, what should I do  to let stratum to support the different device Id?

Thanks a lot!

**Comment by daniele-moro** [comment]
As you mentioned, ONOS supports specifying a different `device_id` in the management address in the netcfg.
Here https://docs.sd-fabric.org/master/configuration/chassis.html#node you can find more information about the meaning of different fields in the Stratum chassis config.
About supporting different device ID in Stratum, I would suggest asking the question in the stratum mailing list (https://groups.google.com/a/opennetworking.org/g/stratum-dev/?pli=1) or stratum repository (https://github.com/stratum/stratum).

Edit: I saw you already asked in the Stratum repo (https://github.com/stratum/stratum/issues/987). Closing this issue here.
